In [ ]:
#import statements

In [1]:
import numpy as np

In [ ]:
# 1-a) Create an 1-d array named 'arr_int' of integers from 45 to 55 inclusive
# 1-b) Read back first 4 elements of 'arr_int'
# 1-c) Read back last element of 'arr_int'

In [2]:
arr_int = np.arange(45,56)

In [4]:
arr_int[:4]

array([45, 46, 47, 48])

In [6]:
arr_int[-1]

55

In [ ]:
# 2-a) Create a 1-d array named 'arr_1' of 12 values from the random-normal distribution
# 2-b) Create a boolean array named ' arr_1_bool' which has "True" where the value in 'arr_1' is greater than 0.5
# 2-c) Reshape the 1-d array 'arr_1' to a 3 row, 4 column 2-d array called 'arr_2'

In [8]:
arr_1 = np.random.randn(12)

In [12]:
arr_1

array([-1.5989525 , -0.54302681,  2.39361316,  0.89035603, -1.76291365,
       -1.67181587, -0.31074967,  0.89303586,  2.34114663,  0.61034613,
       -1.29422628,  0.935431  ])

In [10]:
arr_1_bool = arr_1 > 0.5

In [11]:
arr_1_bool

array([False, False,  True,  True, False, False, False,  True,  True,
        True, False,  True])

In [13]:
arr_2 = arr_1.reshape(3,4)

In [14]:
arr_2

array([[-1.5989525 , -0.54302681,  2.39361316,  0.89035603],
       [-1.76291365, -1.67181587, -0.31074967,  0.89303586],
       [ 2.34114663,  0.61034613, -1.29422628,  0.935431  ]])

In [ ]:
# 3-a) Add first 4 elements of 'arr_int' to first row of 'arr_2'. Store the result as 'arr_3'
# 3-b) Find the mean of 'arr_3'

In [15]:
arr_3 = arr_int[:4] + arr_2[0]

In [16]:
arr_3

array([43.4010475 , 45.45697319, 49.39361316, 48.89035603])

In [18]:
arr_3.mean()

46.785497470290956