In [1]:
# import pandas and numpy libraries

In [2]:
import pandas as pd
import numpy as np

In [3]:
# 1) Create a series 'val_series' with using the following 'values' array:
# values = [2, 5, 3, 10]

In [4]:
values = [2, 5, 3, 10]
series = pd.Series(values)

In [5]:
# 2-a) Create a dataframe 'rand_df' with 5 rows and 3 columns with values from the random normal distribution
# 2-b) Read 4th row
# 2-c) Read 2nd column

In [6]:
rand_df = np.random.randn(5,3)

In [7]:
rand_df

array([[ 0.40110339,  0.37114232,  0.58193461],
       [ 0.80810709,  1.81642709, -0.80632584],
       [ 1.14590798, -0.4333022 ,  0.54641899],
       [-0.12987488,  1.01056714, -0.13256998],
       [-1.56428798,  1.08982563, -0.27801162]])

In [8]:
rand_df[3]

array([-0.12987488,  1.01056714, -0.13256998])

In [9]:
rand_df[:, 1]

array([ 0.37114232,  1.81642709, -0.4333022 ,  1.01056714,  1.08982563])

In [10]:
# 3-a) Create a dataframe 'color_random' using the following statement
# color_random = pd.DataFrame(np.random.randn(4,6), ['Red','Blue','Green','Yellow'], ['a','b','c','d','e','f'])
# 3-b) Read the value at 'Blue' row and 'd' column
# 3-c) Read the values from Green to Yellow and from b to e

In [11]:
color_random = pd.DataFrame(np.random.randn(4,6),['Red','Blue','Green','Yellow'],['a','b','c','d','e','f'])

In [12]:
color_random

a         b         c         d         e         f
Red    -1.129571  0.896528 -0.522826  0.161692 -1.275803  0.073378
Blue   -0.915289 -0.521469  0.621404  2.908812  0.211046 -0.277288
Green  -1.803549 -0.809256 -0.629963 -0.785193  0.281064  1.089619
Yellow -0.960858  0.119132 -0.598460 -0.294364  0.109283  0.179764

In [13]:
color_random.loc['Blue','d']

2.9088124915977875

In [14]:
color_random.loc['Green':'Yellow','b':'e']

b         c         d         e
Green  -0.809256 -0.629963 -0.785193  0.281064
Yellow  0.119132 -0.598460 -0.294364  0.109283

In [15]:
# 4-a) Create a dataframe from the file 'AAPL_data.csv' - provided in course resources
# 4-b) show max, min and average volume

In [16]:
df = pd.read_csv('AAPL_data.csv')

In [17]:
df['volume'].max()      #max volume

51105090

In [18]:
df['volume'].min()      #min volume

18667729

In [19]:
df['volume'].mean()     #mean or average volume

31413306.666666668